# The key of the param distribution should be tne name of the classifier (SVC for SVM, KNeighborsClassifier for KNN etc.)
# Parameter Distribution for SVM
SVC:
  C: [0.1, 1, 10, 100, 200, 250]
  gamma: [20, 30, 40, 50, 60, 70, 80, 90]
  probability: [True] # True only when precalculated probabilities are required for AL_SVM_US

# Parameter Distribution for KNN
KNeighborsClassifier:
  leaf_size: [10,11,12,13,14,15,16,17,18,19,20,21,22,24,25]
  n_neighbors: [3,4,5,6,7,8,9,10]
  p: [1,2]
  weights: ['uniform', 'distance']
  algorithm: ['ball_tree', 'kd_tree']
  n_jobs: [-1]

# Parameter Distribution for CNN
CNN_param:
  batch_size: [512]
  epochs: [35]
  learn_rate: [0.0001]
  activation: ['elu', 'relu', 'LeakyRelu', 'tanh']
  layers: [
            [64, 128],
            [128, 256],
            [64, 128, 256],
            [32, 64, 128],
            [32, 64, 128, 256],
            [128, 64, 32],
            [128, 128, 64, 32],
            [32, 64, 64, 32]
  ]

# Parameter Distribution for Random Forest
RandomForestClassifier:
  n_estimators: [100, 200, 400, 600, 800, 1000]
  n_jobs: [-1]

# Parameter Distribution for HDBSCAN
HDBSCAN:
  min_cluster_size: [3,5,7,9,11,15,17,20,23,25,30]
#  min_cluster_size: [3,5,7,9,11]
#  min_samples: [12,15,18,21,24,27,30,33,36,39,42,45,48]
  min_samples: [~, 1,3,5,7,9,12,15,17]
  gen_min_span_tree: [True]
  core_dist_n_jobs: [-1]
  algorithm: ['generic']
